### PR TITLE
Added User, Category, Activities models and endpoints for Category, Activities and tests.

### LINKED ISSUE #35: Stworzenie komendy "populate", generującej testowe dane
Trzeba przygotować komendę uruchamianą z manage.py, która będzie generowała testowe dane i insertowała je do bazy. Komenda powinna przyjmować opcje pozwalające na wpływanie na sposób generowania danych (np. --seed, --activities_count, coś w tym stylu).
Na tym etapie wystarczy możliwość uruchomienia tej komendy. Implementacja generowania danych jest tu: https://github.com/Szade-Organization/BetterCalendar-API/issues/37

### LINKED ISSUE #37: Implementacja generowania danych testowych (populate)
Wymaga: https://github.com/Szade-Organization/BetterCalendar-API/issues/35

Właściwie dalszy ciąg issue 35. Należy dodać generowanie danych testowych i insertowanie ich do bazy.

### PR DESCRIPTION
**Pull request by WojciechSzade**

### CODE REVIEW

**Comment by mateuszskoczek** [comment]
Na moje oko kod wygląda ok, tylko w sumie jak są jakieś zmiany w modelu to przydałoby się od razu stworzyć jakieś przykładowe dane w bazie. Więc jak robiłeś jakieś inserty do swojej lokalnej bazy podczas testowania tych zmian to można by było te zmiany wyeksportować i wrzucić skrypty z tymi jsonami do repo z bazą.

**Review by mateuszskoczek — APPROVED** [review]

**Comment by mateuszskoczek** [comment]
Daję akcepta, ale zostawiam jeszcze niezmergowane, żebyś dał znać co o tym myślisz, bo według mnie to przydałoby się dodać te przykładowe dane do bazy jeszcze przed wrzuceniem zmian w API do mastera.

**Comment by WojciechSzade** [comment]
Tak, postaram się przygotować skrypt do bazy

**Comment by WojciechSzade** [comment]
Eleganckie robi teraz:

>    {
        "category": 4,
        "date_created": "2023-12-08T16:28:39.420000Z",
        "date_end": "2024-01-13T18:30:10.229000Z",
        "date_modified": "2023-12-08T16:28:39.420000Z",
        "date_start": "2023-06-04T10:47:39.816000Z",
        "description": "Participating in a cooking class to learn new recipes.",
        "id": 253,
        "importance_level": "C",
        "is_planned": true,
        "length": "223 07:42:30.413244",
        "name": "Cooking class",
        "user": 4
    },
    {
        "category": 8,
        "date_created": "2023-12-08T16:28:39.462000Z",
        "date_end": "2023-09-22T14:30:49.047000Z",
        "date_modified": "2023-12-08T16:28:39.462000Z",
        "date_start": "2023-01-22T21:34:13.129000Z",
        "description": "Conducting research for academic or professional purposes.",
        "id": 254,
        "importance_level": "S",
        "is_planned": false,
        "length": "242 16:56:35.918779",
        "name": "Academic research",
        "user": 4
    },
    {
        "category": 3,
        "date_created": "2023-12-08T16:28:39.519000Z",
        "date_end": "2024-04-22T06:58:08.644000Z",
        "date_modified": "2023-12-08T16:28:39.519000Z",
        "date_start": "2023-08-29T02:10:00.541000Z",
        "description": "Completing various errands and tasks outside the home.",
        "id": 255,
        "importance_level": "W",
        "is_planned": false,
        "length": "237 04:48:08.103165",
        "name": "Running errands",
        "user": 4
    },
    {
        "category": 3,
        "date_created": "2023-12-08T16:28:39.571000Z",
        "date_end": "2024-08-10T07:27:16.392000Z",
        "date_modified": "2023-12-08T16:28:39.571000Z",
        "date_start": "2024-07-28T08:20:39.666000Z",
        "description": "Exploring and tasting different craft beers.",
        "id": 256,
        "importance_level": "W",
        "is_planned": false,
        "length": "12 23:06:36.726536",
        "name": "Craft beer tasting",
        "user": 4
    },
    {
        "category": 5,
        "date_created": "2023-12-08T16:28:39.614000Z",
        "date_end": "2024-01-31T10:20:18.420000Z",
        "date_modified": "2023-12-08T16:28:39.614000Z",
        "date_start": "2023-12-14T13:10:58.901000Z",
        "description": "Working on personal projects or hobbies.",
        "id": 257,
        "importance_level": "W",
        "is_planned": false,
        "length": "47 21:09:19.518572",
        "name": "Personal project work",
        "user": 4
    },
    {
        "category": 3,
        "date_created": "2023-12-08T16:28:39.655000Z",
        "date_end": "2024-06-01T23:43:54.026000Z",
        "date_modified": "2023-12-08T16:28:39.655000Z",
        "date_start": "2024-05-10T09:13:32.805000Z",
        "description": "Designing and creating a new board game.",
        "id": 258,
        "importance_level": "M",
        "is_planned": true,
        "length": "22 14:30:21.221025",
        "name": "Board game creation",
        "user": 4
    },
    {
        "category": 5,
        "date_created": "2023-12-08T16:28:39.696000Z",
        "date_end": "2024-10-11T02:27:38.760000Z",
        "date_modified": "2023-12-08T16:28:39.696000Z",
        "date_start": "2024-08-14T05:44:28.869000Z",
        "description": "Conducting research for academic or professional purposes.",
        "id": 259,
        "importance_level": "W",
        "is_planned": false,
        "length": "57 20:43:09.891924",
        "name": "Academic research",
        "user": 3
    },
    {
        "category": 3,
        "date_created": "2023-12-08T16:28:39.742000Z",
        "date_end": "2024-12-07T11:35:57.919000Z",
        "date_modified": "2023-12-08T16:28:39.742000Z",
        "date_start": "2024-12-07T03:25:55.567000Z",
        "description": "Participating in a community cleanup or environmental initiative.",
        "id": 260,
        "importance_level": "C",
        "is_planned": true,
        "length": "08:10:02.352220",
        "name": "Community cleanup",
        "user": 3
    },
    {
        "category": 7,
        "date_created": "2023-12-08T16:28:39.787000Z",
        "date_end": "2024-01-19T16:32:54.823000Z",
        "date_modified": "2023-12-08T16:28:39.787000Z",
        "date_start": "2024-01-11T13:21:33.348000Z",
        "description": "Participating in a charity run or marathon event.",
        "id": 261,
        "importance_level": "S",
        "is_planned": true,
        "length": "8 03:11:21.475510",
        "name": "Charity run",
        "user": 4
    },
    {
        "category": 5,
        "date_created": "2023-12-08T16:28:39.830000Z",
        "date_end": "2024-12-05T22:38:36.303000Z",
        "date_modified": "2023-12-08T16:28:39.830000Z",
        "date_start": "2024-11-06T01:58:04.916000Z",
        "description": "Watching documentaries for educational or informative content.",
        "id": 262,
        "importance_level": "S",
        "is_planned": true,
        "length": "29 20:40:31.387398",
        "name": "Documentary watching",
        "user": 3
    },
    {
        "category": 6,
        "date_created": "2023-12-08T16:28:39.874000Z",
        "date_end": "2023-12-17T23:09:25.136000Z",
        "date_modified": "2023-12-08T16:28:39.874000Z",
        "date_start": "2023-05-10T23:10:28.646000Z",
        "description": "Engaging in photography and capturing images.",
        "id": 263,
        "importance_level": "M",
        "is_planned": true,
        "length": "220 23:58:56.490562",
        "name": "Photography session",
        "user": 4
    },
    {
        "category": 4,
        "date_created": "2023-12-08T16:28:39.919000Z",
        "date_end": "2024-11-03T22:59:17.961000Z",
        "date_modified": "2023-12-08T16:28:39.919000Z",
        "date_start": "2024-10-02T21:31:12.240000Z",
        "description": "Attending an event to network with professionals in the industry.",
        "id": 264,
        "importance_level": "M",
        "is_planned": true,
        "length": "32 01:28:05.721015",
        "name": "Networking event",
        "user": 4
    }
]

**Pull request merged**
